name: kasuwa
description: A cross-platform online marketplace app
publish_to: 'none' # Remove if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0 
  provider: ^6.1.5 
  cached_network_image: ^3.4.1
  intl: ^0.20.2 
  shared_preferences: ^2.5.3 
  connectivity_plus: ^6.1.4
  material_design_icons_flutter: ^7.0.7296
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  google_nav_bar: ^5.0.7
  timeago: ^3.7.1
  share_plus: ^10.1.4
  webview_flutter: ^4.13.0
  image_picker: ^1.1.2
  fl_chart: ^0.71.0
  flutter_secure_storage: ^9.2.4
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
 
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
